### ISSUE TITLE
No Flatpak or RPM support

### ISSUE THREAD

**Issue by yerbestpal** [felicianotech/pocket-casts-desktop-app#10]
This excludes Fedora-based distributions.

**Comment by felicianotech** [comment]
Fedora users can install the Snap. https://docs.snapcraft.io/installing-snap-on-fedora

**Comment by lolrepeatlol** [comment]
Can you reconsider this? I refuse to use Snaps because it's controlled by Canonical and Canonical only, as its backend is closed-source. I would love Flatpak support. Flatpak is made by the open source community.

**Comment by felicianotech** [comment]
I'm still not sold on the need for Flatpak at the moment but I can definitely create an RPM package. I made an Issue to track this: https://github.com/felicianotech/pocket-casts-desktop-app/issues/34

**Comment by nadir-yttrium** [comment]
I'd just like to express my support for a flatpak.

**Comment by hadess** [comment]
FYI, a Flatpak is available on Flathub:
https://flathub.org/apps/details/tech.feliciano.pocket-casts
