### ISSUE TITLE
No app icon in .deb installation

### ISSUE THREAD

**Issue by robertorolo** [felicianotech/pocket-casts-desktop-app#11]

**Comment by owenlejeune** [comment]
I'm seeing this issue as well

**Comment by akhilsukh01** [comment]
Just installed the new version 0.4.0 and have been having the same issue with the .deb package, haven't tried snap version yet.

**Comment by felicianotech** [comment]
This will be the next item I work on for this project. :+1:

**Comment by felicianotech** [comment]
@robertorolo @owenlejeune This should be fixed in the v0.4.1 .deb. If either of you can confirm, I would appreciate it.
