### ISSUE TITLE
Tray Icon and Multiple Instances

### ISSUE THREAD

**Issue by elephant-overlord** [felicianotech/pocket-casts-desktop-app#16]
Personal preferences aside, the new tray icon makes it very obvious when multiple instances have been started. Whenever you close the window and re-run the app, you get an additional tray icon (I have 3 right now). 

![Screenshot from 2019-09-22 10-42-15](https://user-images.githubusercontent.com/34039206/65384703-ab5c6b80-dd25-11e9-8188-5dc2a62ab695.png)

The app should either be single-instance or at least allow to disable the tray icon, which is pretty useless in many desktop environments anyway, as the icon is already showing in the dock/panel.

**Comment by danieltomasz** [comment]
+1 for single instance (with tray icon)

**Comment by lesthack** [comment]
@elephant-overlord what OS are you using?

**Comment by felicianotech** [comment]
I've confirmed this for Ubuntu 19.04 running via snap.

**Comment by felicianotech** [comment]
Thoughts on how this should work?

In PR #18 I provided some thoughts on what I would like. Basically I said:

> I think the desired behavior here is when closing the window, the instance should fully quit, tray icon included.

My main question is, when you close the Pocket Casts main window (not minimize but actually close), should the tray icon go away too (close the app completely) or should it stick around?

**Comment by danieltomasz** [comment]
So now I have another behavior on Ubuntu 18.04: 
1. The tray icon doesn't appear on tray (but this is general thing, probably I changed something in gnome, other apps also doesn't appear on tray) 
2. But after closing the window the program is still active :
a) `pidof` gives me many  running instances of `pocket-casts` processes
b) when starting new instance  of the app, the app ask for password again
c) when killing all  running instances it starts without asking for a user and  password  

for me the best option would that the icon stays (with the menu option there to completely close off), but I could accept other solutions :) 

Maybe the whole problem is caused that there are many instances of the electron app allowed?
I have a similar problem when I did custom site packaging in electron.

**Comment by elephant-overlord** [comment]
Gnome only supports tray icons through extensions afaik, so I personally don‘t need/want them. Imo, tray icons should be reserved for long running background services which include a GUI, e.g. backup software. For everything else, Gnome uses the dock, where I can see running apps, including every other media player.

If you decide that the icon is needed (fine by me, I‘m just happy I can listen to my podcasts ;), I would advocate for the following:

Close button closes to tray, minimize button minimizes to dash/dock. Tray icon menu allows to quit the app completely.

Ideally, there would be an option to disable the tray icon completely.
