### ISSUE TITLE
Bottom bar has a solid black bakground

### ISSUE THREAD

**Issue by PHLAK** [felicianotech/pocket-casts-desktop-app#23]
The active podcast bar (where the play/pause buttons and seek bar is located) has a solid black background in Ubuntu 20.04 when installed through the snap package.

    sudo snap install pocket-casts

![Screenshot 2020-05-04 13:32:42](https://user-images.githubusercontent.com/53531/81010931-ea01ea80-8e0b-11ea-8cc9-f02eb5e67785.png)

**Comment by tribut** [comment]
This has been fixed for me with v0.4.0

**Comment by PHLAK** [comment]
Thank you!
