### ISSUE TITLE
Add Play/Pause buttons to system tray icon

### ISSUE THREAD

**Issue by felicianotech** [felicianotech/pocket-casts-desktop-app#4]

**Comment by AppelonD** [comment]
Well I installed the latest release 0.2.0 but my media keys dont work.

**Comment by felicianotech** [comment]
Hi @AppelonD,

This issue is not related to what you're referring to.

Can you please open a new issue for this problem and in it state:

- what OS you are using
- how you installed the app
- where are you media buttons? (keyboard, someplace else)

**Comment by lesthack** [comment]
I think that my pull request add this feature.
https://github.com/felicianotech/pocket-casts-desktop-app/pull/13
