### ISSUE TITLE
ARM64 release

### ISSUE THREAD

**Issue by sergioad** [felicianotech/pocket-casts-desktop-app#40]
Hi, could you please make an arm64 snap?

**Comment by hadess** [comment]
I know it's not the same thing, but the Flatpak from Flathub has support for x86_64 and aarch64 (aka arm64):
https://flathub.org/apps/details/tech.feliciano.pocket-casts

**Comment by sergioad** [comment]
Thank you very much, the next time I get plus I will use it

**Comment by felicianotech** [comment]
There will be arm64 builds in the future. I've been pulling back away from snaps so I don't know if the snap will have it. I will let you know when I decide. Regardless, as @hadess mentioned, the Flatpak they made has it.

**Comment by FelicianoTech** [comment]
An arm64 deb is now available on the releases page. An Apt repository is coming for this and when it does, it will also have an arm64 deb.
