### ISSUE TITLE
Unable to open app: error while loading shared libraries: libX11.so.6

### ISSUE THREAD

**Issue by cspipaon** [felicianotech/pocket-casts-desktop-app#49]
I am unable to open the app via GUI or via terminal.

Running `pocket-casts` in terminal returns:
`/snap/pocket-casts/10/pocket-casts: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`

Not sure if this is due to the recent update in my system (Pop! OS 21.04) or something else:
```
uname -srv
Linux 5.11.0-7620-generic #21~1626191760~21.04~55de9c3-Ubuntu SMP Tue Jul 20 22:18:55 UTC 
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute
```

**Comment by felicianotech** [comment]
investigating

**Comment by felicianotech** [comment]
Actually, I see you are using the snap. @cspipaon, can you try installing the `.deb` and seeing how that works for you?

**Comment by cspipaon** [comment]
Hey @felicianotech, I installed the `pocket-casts_0.5.0_amd64.deb` package and it works just fine.
I also removed the snap package, installed it again and it's also working.

I am not sure what is the reason for the error I posted above... Feel free to close the issue (or leave it open), I am not sure what the usual following actions are in these cases.
