### ISSUE TITLE
MPRIS Integration

### ISSUE THREAD

**Issue by cferriby** [felicianotech/pocket-casts-desktop-app#6]
implement media controls using the MPRIS dbus spec so that desktop environments that provide media controls can control the playback. 

There is node package called mpris-service that I believe could be used to achieve this.

**Comment by AppelonD** [comment]
I really would love Media Controls to work, maybe you can finde some inspiration here
github.com:MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-.git

This a nice Desktop player for Google Play Music

**Comment by p-kolacz** [comment]
Maybe this will help:
```
globalShortcut.register('MediaPlayPause', () => {
        win.webContents.executeJavaScript("document.querySelector('.play_pause_button').click()")
})

globalShortcut.register('MediaPreviousTrack', () => {
	win.webContents.executeJavaScript("document.querySelector('.skip_back_button').click()")
})

globalShortcut.register('MediaNextTrack', () => {
	win.webContents.executeJavaScript("document.querySelector('.skip_forward_button').click()")
})
```

**Comment by felicianotech** [comment]
See PR #8.

While I didn't technically implement support for MPRIS, I did add support for the media buttons to control a playing podcast.

Thank you @p-kolacz.
