### ISSUE TITLE
Publish New Release

### ISSUE THREAD

**Issue by ciferkey** [felicianotech/pocket-casts-desktop-app#64]
Hello. Appreciate your work on this project so I can have a desktop version on Linux.

Is it possible to publish a new release? The [last one](https://github.com/felicianotech/pocket-casts-desktop-app/releases/tag/v0.5.0) was in 2020.

For Nix [we repackage](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/applications/audio/pocket-casts/default.nix) the deb version. However the current release uses a version of Electron that is flagged as insecure so we're getting [build failures](https://github.com/NixOS/nixpkgs/issues/175999#issuecomment-1145389471).

**Comment by FelicianoTech** [comment]
Published v0.6.0. This is a minor release just bumping things like Electron. A more substantial release is in the works.
