### ISSUE TITLE
Media keys only work once

### ISSUE THREAD

**Issue by gadtfly** [felicianotech/pocket-casts-desktop-app#9]
On Ubuntu 18.10 (and reported in several other distros by users of other Electron apps):

Only the first use of a media key (play/pause, next, previous) works as intended.

Subsequent presses fail to make it to the app.

This appears to be an issue with Electron's `globalShortcut`, that manifests in systems using DBus (recent Ubuntus, I think any Gnome setup, and others).

There are a few reported workarounds involving talking to DBus directly.

See:

https://github.com/electron/electron/issues/12415
https://github.com/electron/electron/issues/10159
https://github.com/electron/electron/issues/5268
https://github.com/electron/electron/issues/3941

**Comment by felicianotech** [comment]
Looking into this. Thank you for reporting.

**Comment by gadtfly** [comment]
I've tried the snap, the .deb, and `electron-builder`ing it from your source.  The issue is indeed effecting me in all those cases, on Ubuntu 18.10.

**Comment by salvadornico** [comment]
I'm noticing the same on 18.04, from the snap install.

**Comment by hasher-hasher** [comment]
I'm using Ubuntu 18.04 with .deb installation and i'm not having this issue. Did you tested with Ubuntu 18.04 using the .deb package?

**Comment by klemm89** [comment]
I'm running the snap on pop!_OS (Ubuntu 18.04 LTS) and it fails after the initial media key as well. Is there any log file for snaps I could provide you?

**Comment by felicianotech** [comment]
I can reproduce this issue on Ubuntu 19.04 now. I'm still waiting for Electron to figure this out. I tried to implement one of the workarounds listed but couldn't get it to work.

**Comment by iuymatiao** [comment]
I'm also running into issues where the media controls on my keyboard stop working after the first key press. Not sure if it helps, but maybe you can take a look at this [other project that's an Electron wrapper for Pocket Casts](https://github.com/jgierer12/pocket-casts-linux). The project's been abandoned, but the media controls do still work for me (except curiously the "Previous Track" key).

Hopefully this helps in any way.

**Comment by tribut** [comment]
MPRIS would certainly be the most comprehensive solution.

**Comment by fuadsaud** [comment]
I've forked https://github.com/jgierer12/pocket-casts-linux and fixed some annoying MPRIS bugs. If there's interest, it might be possible to port the MPRIS implementation from that repo into this one.

**Comment by felicianotech** [comment]
@fuadsaud A PR to this repo so that I may test these changes is definitely welcome.

**Comment by FelicianoTech** [comment]
👁️
