### ISSUE TITLE
Impossible to scroll

### ISSUE THREAD

**Issue by nclm** [felicianotech/pocket-casts-desktop-app#91]
Hi, thanks for making this app!

I installed it yesterday but I have an issue: I cannot scroll within the app.

Scrolling works perfectly in other apps, including other Electron apps.

(this is on Ubuntu 21.10 / GNOME 45)

**Comment by hadess** [comment]
I can confirm this using the Flatpak package from Flathub.

**Comment by FelicianoTech** [comment]
Hey. Thanks for the report.

@nclm Which install method did you use and which version of this app?

@hadess What distro and desktop are you using?

**Comment by FelicianoTech** [comment]
v0.7.0 is published on the GitHub releases page. Can anyone let me know if this is still an issue with the new release?

**Comment by aidanjmaunder** [comment]
> v0.7.0 is published on the GitHub releases page. Can anyone let me know if this is still an issue with the new release?

I just grabbed v0.7.0, and on Pop!_OS 22.04 it's now working again, thanks a lot for the fix!

![Screenshot from 2023-10-26 11-24-26](https://github.com/felicianotech/pocket-casts-desktop-app/assets/12162800/3cf38801-94d0-4ffa-8667-bd52f0121aa7)

**Comment by nclm** [comment]
Great, thanks a lot! I’ll try it when it’s updated on Flathub :)

**Comment by FelicianoTech** [comment]
Awesome
